import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { readPackage } from "./read-package.mjs";

const { absolute, bytes, zip, metadata, resource } = await readPackage();
const config = JSON.parse(await readFile("pbiviz.json", "utf8"));
const capabilities = JSON.parse(await readFile("capabilities.json", "utf8"));
assert.equal(resource.visual.guid, config.visual.guid);
assert.equal(resource.visual.version, config.visual.version);
assert.equal(resource.apiVersion, "5.11.0");
assert.equal(resource.apiVersion, config.apiVersion);
assert.deepEqual(resource.capabilities.privileges, []);
assert.deepEqual(resource.capabilities.dataRoles, capabilities.dataRoles);
assert.equal(config.visual.supportUrl, "https://atlynco.github.io/atlyn-powerbi-support/docs/faq/");
assert.equal(resource.visual.supportUrl, config.visual.supportUrl);
assert.equal(resource.author.email, "atlyn.help@gmail.com");
assert.equal(metadata.version, config.visual.version);
assert.equal(metadata.visual.guid, config.visual.guid);
assert.equal(metadata.resources.length, 1);
assert.ok(zip.file(metadata.resources[0].file));
assert.deepEqual(resource.externalJS, []);
assert.ok(resource.content.js.length > 10000);
assert.ok(resource.content.js.includes("Permission is hereby granted"), "Distribution must retain full MIT permission notices");
assert.ok(resource.content.css.includes(".atlyn-overlap"));
assert.ok(resource.content.iconBase64.startsWith("data:image/png;base64,"));
const icon = Buffer.from(resource.content.iconBase64.slice("data:image/png;base64,".length), "base64");
assert.deepEqual(icon.subarray(0, 8), Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
assert.equal(icon.readUInt32BE(16), 20);
assert.equal(icon.readUInt32BE(20), 20);
assert.deepEqual(icon, await readFile(path.join("assets", "icon.png")));
assert.ok(resource.stringResources["en-US"].Title);
assert.ok(resource.stringResources["fr-FR"].Title);
assert.deepEqual(Object.keys(resource.stringResources["en-US"]).sort(), Object.keys(resource.stringResources["fr-FR"]).sort());
assert.ok(!Object.keys(zip.files).some(name => /node_modules|\.map$|\.ts$/.test(name)));
assert.ok(!/PRIVATE KEY|PowerBICustomVisualTestPass|\.pfx/.test(resource.content.js), "Package must not contain development keys");
const networkOrDynamicCode = /\b(?:eval|XMLHttpRequest|WebSocket|fetch|sendBeacon|importScripts)\s*\(|\bnew\s+Function\s*\(/;
assert.ok(!networkOrDynamicCode.test(resource.content.js), "Unexpected runtime network/dynamic-code primitive");
assert.ok(!/@import\b|url\s*\(\s*["']?https?:/i.test(resource.content.css), "External CSS resource");
const hash = createHash("sha256").update(bytes).digest("hex");
await writeFile(path.join("dist", "artifact.sha256"), `${hash}  ${path.basename(absolute)}\n`);
console.log(`Package structure and local policy assertions passed (not Microsoft certification).\n${absolute}\nSHA256 ${hash}`);
